// Package guess implements the /guess number-guessing game: the bot
// picks a secret number in [Min, Max] per chat, and any member can
// submit a guess. The first correct guess wins, the round ends, and an
// optional per-chat win leaderboard is bumped.
//
// The secret is generated by the bot (unlike dice, where Telegram is the
// source of truth) so randomness is injectable for deterministic tests.
package guess

import (
	"context"
	"errors"
	"time"
)

// Min and Max bound the secret number (inclusive). Guesses outside this
// range are rejected with a friendly hint rather than counted as a miss.
const (
	Min = 1
	Max = 100
)

// StaleAfter is how long an untouched round may live before the next
// /guess (with no argument) is allowed to abandon it and start fresh.
// Without this a forgotten round would block the command forever.
const StaleAfter = time.Hour

// ErrNotFound signals that no round exists for the chat. Treated as "no
// active round" by callers.
var ErrNotFound = errors.New("guess: no round for chat")

// Round is the per-chat game state. At most one Round exists per chat;
// Active distinguishes a live round from a finished one that is kept
// only so a stale-finished record does not linger (callers may also
// just delete it).
type Round struct {
	AbsChatID int64     `json:"abs_chat_id"`
	Secret    int       `json:"secret"`
	Active    bool      `json:"active"`
	StartedAt time.Time `json:"started_at"`
	Attempts  int       `json:"attempts"`
}

// WinEntry is one user's win tally in one chat (optional tiny
// leaderboard, mirrors the quiz leaderboard shape).
type WinEntry struct {
	AbsChatID int64     `json:"abs_chat_id"`
	UserID    int64     `json:"user_id"`
	Username  string    `json:"username,omitempty"`
	FirstName string    `json:"first_name,omitempty"`
	Wins      int64     `json:"wins"`
	LastWonAt time.Time `json:"last_won_at"`
}

// Store is the persistence contract. The bbolt implementation lives in
// internal/storage; tests use an in-memory map.
type Store interface {
	// GetRound returns the chat's round or ErrNotFound when none exists.
	GetRound(ctx context.Context, absChatID int64) (*Round, error)
	// PutRound unconditionally writes the round.
	PutRound(ctx context.Context, r Round) error
	// DeleteRound removes the chat's round. Deleting a missing round is
	// a no-op (no error).
	DeleteRound(ctx context.Context, absChatID int64) error
	// IncrementWin creates or bumps the user's win tally for the chat.
	IncrementWin(ctx context.Context, e WinEntry) error
	// TopWins returns up to limit win entries for the chat, highest
	// first. limit<=0 returns all.
	TopWins(ctx context.Context, absChatID int64, limit int) ([]WinEntry, error)
}

// Rand is the minimal randomness surface the service needs. *rand.Rand
// satisfies it; tests pass a deterministic stub.
type Rand interface {
	Intn(n int) int
}
