package bot

// YouTube `si=` link sanitizer.
//
// Telegram clients append a `si` share-tracking parameter to YouTube
// links generated by the native share sheet. When a supergroup message
// carries such a link the bot copies its content with only `si`
// parameters removed. Media is copied server-side, without reuploading.
// Captions that exceed the bot caption limit are sent as separate text
// messages with their entities preserved. Only after every part has been
// sent does the bot delete the original. Any failure retains the original
// and posts no sanitizer notice.
//
// The host check is scoped: only YouTube hosts are sanitized, so a
// Spotify `?si=` (or any other service that uses the same param name)
// is never touched.
//
// Design notes:
//   - URL/entity transformation lives in youtube_entities.go
//     (StripShareTracking, SanitizeMessageText). This file orchestrates:
//     it decides whether a message is representable and, if so, sends
//     the cleaned copy and deletes the original last.
//   - edited_message: OUT OF SCOPE. The router only feeds
//     update.Message here; an edit that introduces a tracked link is
//     not re-sanitized. Explicit gap, not silently ignored.
//   - albums (MediaGroupID != "") are not rewritten: copyMessage on one
//     item would split the group. They are retained untouched.
//   - Manually forwarded channel posts (ForwardOrigin set) remain
//     eligible; the copy reproduces content, not the forward header.

import (
	"context"
	"log/slog"
	"regexp"
	"strings"

	"github.com/mymmrac/telego"
	th "github.com/mymmrac/telego/telegohandler"

	"github.com/veschin/bidlobot/internal/shared"
)

// youtubeHosts is the exact set of hosts whose `si` parameter is
// share-tracking. Host comparison is lower-cased with a leading "www."
// or "m." stripped. Any host not in this set is left untouched, which
// is what keeps Spotify/other `si=` links safe.
var youtubeHosts = map[string]struct{}{
	"youtube.com":          {},
	"youtu.be":             {},
	"youtube-nocookie.com": {},
	"music.youtube.com":    {},
}

// urlScanRe finds bare http(s) URLs and scheme-less youtu.be /
// youtube.com style links in plain text. It is intentionally
// conservative: it stops at whitespace and a small set of trailing
// punctuation so a link at the end of a sentence ("...watch?v=x&si=y.")
// does not swallow the period. Angle/paren wrappers are also excluded.
var urlScanRe = regexp.MustCompile(`(?i)\b((?:https?://|www\.|m\.)?(?:[a-z0-9-]+\.)*(?:youtube\.com|youtu\.be|youtube-nocookie\.com)\b[^\s<>"')\]]*)`)

// trailingPunct is stripped from a scanned token's tail so sentence
// punctuation that the regex may still catch (e.g. a trailing ")",
// handled above, or "," "." "!" "?") is not folded into the URL and
// then re-emitted. The stripped suffix is re-appended verbatim after
// cleaning so the surrounding text is preserved exactly.
const trailingPunct = ".,!?;:"

// isYouTubeHost lower-cases host, drops any port, strips a single
// leading "www." or "m." label, and checks the exact allowlist.
func isYouTubeHost(host string) bool {
	host = strings.ToLower(host)
	if i := strings.IndexByte(host, ':'); i >= 0 {
		host = host[:i]
	}
	switch {
	case strings.HasPrefix(host, "www."):
		host = host[len("www."):]
	case strings.HasPrefix(host, "m."):
		host = host[len("m."):]
	}
	_, ok := youtubeHosts[host]
	return ok
}

// youtubeCopySender is the narrow rate-limited surface the YouTube
// sanitizer needs. Unlike the shared youtubeMediaSender (which the
// TikTok/X reposter uses for file_id uploads), the sanitizer never
// uploads media: it posts text with corrected entities, asks Telegram
// to copy the original message server-side (copyMessage preserves the
// original media), and deletes the original only after a confirmed
// successful send/copy. Production wires *tgclient.Client; a sender
// without CopyMessage capability is treated as "cannot sanitize" and
// the original is kept.
type youtubeCopySender interface {
	SendMessage(ctx context.Context, params *telego.SendMessageParams) (*telego.Message, error)
	CopyMessage(ctx context.Context, params *telego.CopyMessageParams) (*telego.MessageID, error)
	DeleteMessage(ctx context.Context, params *telego.DeleteMessageParams) error
}

// sanitizedPost carries the corrected text/caption and their corrected
// entity lists from the pure decision gate to the send/copy step.
type sanitizedPost struct {
	text         string
	textEntities []telego.MessageEntity
	caption      string
	capEntities  []telego.MessageEntity
}

// youtubeSanitizer is the supergroup middleware. Signature mirrors
// statsCountHandler's use in routes.go (a th.Handler closing over App).
//
// Per incoming update.Message in a supergroup it:
//   - skips bots / anonymous-admin / channel-as-sender / no-sender,
//     consistent with the stats exclusion set;
//   - computes the sanitized text/entities and caption/entities; if
//     nothing changed, passes through;
//   - on change: preflights representability, posts ONE cleaned copy
//     (text or server-side media copy), and deletes the original only
//     after that copy is confirmed. Any failure keeps the original and
//     posts no notice.
//
// It always calls ctx.Next(update) so sibling middleware (membership,
// stats) still run. Deleting the chat message does not remove the
// in-flight update object; keeping the chain consistent matches how
// statsCountHandler behaves.
func youtubeSanitizer(a *App) th.Handler {
	return func(thctx *th.Context, update telego.Update) error {
		if act, plan := sanitizeDecision(update.Message); act {
			handleSanitize(thctx.Context(), a.youtubeCopySender(), a.log,
				update.Message, plan)
		}
		// Always continue the chain so sibling middleware (membership,
		// stats) still run. Deleting the chat message does not remove
		// the in-flight update; keeping the chain consistent matches
		// statsCountHandler.
		return thctx.Next(update)
	}
}

// sanitizeDecision is the pure, fully unit-testable gate. It applies
// the same exclusion set as the stats counter (no sender / bot /
// anonymous-admin / channel-as-sender) and computes the sanitized
// text/entities and caption/entities. It returns act=false when the
// message must be passed through untouched - including when the
// entity-aware transformation reports an error, in which case the
// original is retained as-is. The input message and its entity slices
// are never mutated.
func sanitizeDecision(msg *telego.Message) (bool, *sanitizedPost) {
	if msg == nil {
		return false, nil
	}
	if msg.From == nil || msg.From.IsBot ||
		shared.IsAnonymousAdmin(msg.From.ID) || msg.SenderChat != nil {
		return false, nil
	}
	newText, newEntities, textChanged, err := SanitizeMessageText(msg.Text, msg.Entities)
	if err != nil {
		return false, nil
	}
	newCaption, newCapEntities, capChanged, err := SanitizeMessageText(msg.Caption, msg.CaptionEntities)
	if err != nil {
		return false, nil
	}
	if !textChanged && !capChanged {
		return false, nil
	}
	return true, &sanitizedPost{
		text:         newText,
		textEntities: newEntities,
		caption:      newCaption,
		capEntities:  newCapEntities,
	}
}

// youtubeCopySender returns the sanitizer's narrow send surface. The
// production sender is *tgclient.Client, which implements SendMessage,
// CopyMessage and DeleteMessage; anything else (including the
// text-only fallback used by TikTok/X) lacks copy capability, and a
// nil result makes handleSanitize retain the original. The type
// assertion lives in one place rather than in the handler.
func (a *App) youtubeCopySender() youtubeCopySender {
	if s, ok := a.sender.(youtubeCopySender); ok {
		return s
	}
	return nil
}

// preflightReason reports why a changed message cannot be safely copied.
// Lengths are checked on the prepared text; long media captions use the
// separate-text path. Checked before any send: an unsafe shape keeps the
// original with no notice, never a partial rewrite.
func preflightReason(msg *telego.Message, plan *sanitizedPost) string {
	switch {
	case msg.GetMessageID() <= 0:
		return "unusable original id"
	case msg.MediaGroupID != "":
		return "album item"
	case msg.PaidMedia != nil || msg.PaidStarCount != 0 || msg.IsPaidPost:
		return "paid media or paid post"
	case msg.ReplyMarkup != nil:
		return "inline keyboard not preservable"
	case msg.Invoice != nil || msg.SuccessfulPayment != nil || msg.RefundedPayment != nil:
		return "unsupported attached content"
	case msg.HasMediaSpoiler:
		return "media spoiler not preservable"
	case msg.IsAutomaticForward:
		return "automatic channel forward"
	case msg.Quote != nil && msg.ReplyToMessage == nil:
		return "quote without local reply"
	case msg.ExternalReply != nil || msg.ReplyToStory != nil ||
		msg.ReplyToChecklistTaskID != 0 || msg.ReplyToPollOptionID != "":
		return "unsupported reply context"
	case utf16Length(plan.text) > 4096:
		return "cleaned text over 4096 UTF-16 units"
	case sanitizedContentKind(msg) == "":
		return "unsupported content kind"
	}
	return ""
}

// sanitizedContentKind classifies the message into a shape the
// sanitizer can reproduce: one of the caption-bearing media kinds (all
// preserved server-side by copyMessage) or a plain text message. "" is
// returned for everything else (polls, contacts, dice, service
// messages, ...) which is never rewritten.
func sanitizedContentKind(msg *telego.Message) string {
	switch {
	case len(msg.Photo) > 0:
		return "photo"
	case msg.Video != nil:
		return "video"
	case msg.Animation != nil:
		return "animation"
	case msg.Document != nil:
		return "document"
	case msg.Audio != nil:
		return "audio"
	case msg.Voice != nil:
		return "voice"
	case msg.Text != "":
		return "text"
	default:
		return ""
	}
}

// copyReplyParams preserves an ordinary same-chat reply target, and a
// local quote reply's quoted text/entities/position, on the copy.
// Genuinely unsupported reply contexts (external replies, stories,
// checklist tasks, poll options; and quotes without a local reply
// message) are rejected by preflight instead of being partially
// recreated.
func copyReplyParams(msg *telego.Message) *telego.ReplyParameters {
	if msg.ReplyToMessage == nil {
		return nil
	}
	rp := &telego.ReplyParameters{
		MessageID: msg.ReplyToMessage.GetMessageID(),
		ChatID:    telego.ChatID{ID: msg.Chat.ID},
	}
	if msg.Quote != nil {
		rp.Quote = msg.Quote.Text
		rp.QuoteEntities = msg.Quote.Entities
		rp.QuotePosition = msg.Quote.Position
	}
	return rp
}

// sanitizedTextParams builds the text copy: the corrected text and its
// corrected entity offsets, no ParseMode and no HTML escaping (the
// body is the user's own text, only shorter), the original thread and
// protection settings, and the original link-preview settings with a
// cleaned preview URL if the preview pinned a tracked link. The
// original LinkPreviewOptions struct is copied before modification so
// the incoming message object is never mutated.
func sanitizedTextParams(msg *telego.Message, plan *sanitizedPost) *telego.SendMessageParams {
	params := &telego.SendMessageParams{
		ChatID:          telego.ChatID{ID: msg.Chat.ID},
		Text:            plan.text,
		Entities:        plan.textEntities,
		MessageThreadID: msg.MessageThreadID,
		ProtectContent:  msg.HasProtectedContent,
		ReplyParameters: copyReplyParams(msg),
	}
	if msg.LinkPreviewOptions != nil {
		lpo := *msg.LinkPreviewOptions
		if lpo.URL != "" {
			if cleaned, changed := StripShareTracking(lpo.URL); changed {
				lpo.URL = cleaned
			}
		}
		params.LinkPreviewOptions = &lpo
	}
	return params
}

// sanitizedCopyParams builds the server-side media copy. FromChatID/
// MessageID reference the ORIGINAL message, so Telegram reuses the
// original media server-side with no download/reupload; only the
// caption (and its entities) carry the si cleanup. The original
// caption placement, thread, protection and reply context are kept.
func sanitizedCopyParams(msg *telego.Message, plan *sanitizedPost) *telego.CopyMessageParams {
	return &telego.CopyMessageParams{
		ChatID:                telego.ChatID{ID: msg.Chat.ID},
		MessageThreadID:       msg.MessageThreadID,
		FromChatID:            telego.ChatID{ID: msg.Chat.ID},
		MessageID:             msg.GetMessageID(),
		Caption:               plan.caption,
		CaptionEntities:       plan.capEntities,
		ShowCaptionAboveMedia: msg.ShowCaptionAboveMedia,
		ProtectContent:        msg.HasProtectedContent,
		ReplyParameters:       copyReplyParams(msg),
	}
}

// handleSanitize performs the guarded copy + delete. It is split out so
// it is unit-testable with a recording fake sender without driving the
// whole th.Context machinery.
//
// Contract: the original is deleted ONLY after a successful send/copy
// with a positive new message id. A send error, a nil/zero result, a
// missing copy capability or an unsafe preflight shape retains the
// original and posts NO fallback notice. A delete failure after a
// successful copy keeps both messages and logs. Logs carry ids and
// reasons only - never message bodies or URLs.
func handleSanitize(
	ctx context.Context,
	snd youtubeCopySender,
	log *slog.Logger,
	msg *telego.Message,
	plan *sanitizedPost,
) {
	if msg == nil || plan == nil {
		return
	}
	if snd == nil {
		log.Info("youtube sanitizer: no copy-capable sender; original kept",
			"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID())
		return
	}
	if reason := preflightReason(msg, plan); reason != "" {
		log.Info("youtube sanitizer: unrepresentable message kept as-is",
			"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID(), "reason", reason)
		return
	}

	var newID int
	kind := sanitizedContentKind(msg)
	if kind != "text" && utf16Length(plan.caption) > 1024 {
		id, err := copyLongYouTubeCaption(ctx, snd, log, msg, plan)
		if err != nil {
			log.Warn("youtube sanitizer: long caption copy failed; original kept",
				"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID(), "error", err)
			return
		}
		newID = id
	} else if kind == "text" {
		m, err := snd.SendMessage(ctx, sanitizedTextParams(msg, plan))
		switch {
		case err != nil:
			log.Warn("youtube sanitizer: text send failed; original kept",
				"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID(), "error", err)
			return
		case m == nil || m.MessageID <= 0:
			log.Warn("youtube sanitizer: text send returned no id; original kept",
				"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID())
			return
		}
		newID = m.MessageID
	} else {
		id, err := snd.CopyMessage(ctx, sanitizedCopyParams(msg, plan))
		switch {
		case err != nil:
			log.Warn("youtube sanitizer: copy failed; original kept",
				"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID(), "error", err)
			return
		case id == nil || id.MessageID <= 0:
			log.Warn("youtube sanitizer: copy returned no id; original kept",
				"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID())
			return
		}
		newID = id.MessageID
	}

	if err := snd.DeleteMessage(ctx, &telego.DeleteMessageParams{
		ChatID:    telego.ChatID{ID: msg.Chat.ID},
		MessageID: msg.GetMessageID(),
	}); err != nil {
		// The cleaned copy (newID) is already live; we just cannot
		// remove the original. Both stay - never destroy content.
		log.Info("youtube sanitizer: copied but delete failed; original kept",
			"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID(),
			"new_message_id", newID, "error", err)
	}
}

// largestPhotoFileID returns the file_id of the highest-resolution
// PhotoSize so consumers that must re-send a photo by file_id (the
// X-post reposter) keep the original quality. Telegram orders the
// slice ascending but we pick by area defensively rather than trusting
// order.
func largestPhotoFileID(sizes []telego.PhotoSize) string {
	best := sizes[0]
	bestArea := best.Width * best.Height
	for _, s := range sizes[1:] {
		if a := s.Width * s.Height; a > bestArea {
			best, bestArea = s, a
		}
	}
	return best.FileID
}

// youtubeMediaSender is the narrow rate-limited send surface the
// TikTok/X reposter needs. Production wires *tgclient.Client (which
// implements the media sends in addition to SendMessage/DeleteMessage)
// so every repost shares the per-chat rate budget instead of bypassing
// it via the raw *telego.Bot - the same pattern stats.MessageSender and
// GamesSender use. The YouTube sanitizer does NOT use this interface;
// it uses youtubeCopySender (server-side copyMessage, no uploads).
type youtubeMediaSender interface {
	SendMessage(ctx context.Context, params *telego.SendMessageParams) (*telego.Message, error)
	DeleteMessage(ctx context.Context, params *telego.DeleteMessageParams) error
	SendPhoto(ctx context.Context, params *telego.SendPhotoParams) (*telego.Message, error)
	SendVideo(ctx context.Context, params *telego.SendVideoParams) (*telego.Message, error)
	SendAnimation(ctx context.Context, params *telego.SendAnimationParams) (*telego.Message, error)
	SendDocument(ctx context.Context, params *telego.SendDocumentParams) (*telego.Message, error)
	SendMediaGroup(ctx context.Context, params *telego.SendMediaGroupParams) ([]telego.Message, error)
}

// sanitizerSender returns the rate-limited media-capable client. It is
// a method (not a direct a.sender reference in the handler) so the
// narrow interface assertion lives in one place and the type mismatch -
// shared.TelegramAPI lacks the media methods - is resolved here via the
// concrete client. a.sender is the *tgclient.Client; the type assertion
// is safe because production always constructs it so, and a failure is
// surfaced (logged + degraded to text-only) rather than panicking.
func (a *App) sanitizerSender() youtubeMediaSender {
	if s, ok := a.sender.(youtubeMediaSender); ok {
		return s
	}
	// Degraded mode: the configured sender does not expose media sends.
	// Wrap the text/delete surface so the TikTok/X poster can still post
	// text instead of crashing. Logged once per call site by the caller.
	return textOnlySender{a.sender}
}

// textOnlySender adapts a SendMessage/DeleteMessage-only client to the
// media interface by failing media sends with a sentinel error, which
// TikTok/X callers treat as "media send not possible". This keeps the
// feature safe if wiring ever passes a non-media client; it is not the
// expected production path.
type textOnlySender struct {
	api interface {
		SendMessage(ctx context.Context, params *telego.SendMessageParams) (*telego.Message, error)
		DeleteMessage(ctx context.Context, params *telego.DeleteMessageParams) error
	}
}

var errNoMediaSend = &mediaUnsupportedError{}

type mediaUnsupportedError struct{}

func (*mediaUnsupportedError) Error() string {
	return "tgclient: media send not supported by configured sender"
}

func (t textOnlySender) SendMessage(ctx context.Context, p *telego.SendMessageParams) (*telego.Message, error) {
	return t.api.SendMessage(ctx, p)
}
func (t textOnlySender) DeleteMessage(ctx context.Context, p *telego.DeleteMessageParams) error {
	return t.api.DeleteMessage(ctx, p)
}
func (textOnlySender) SendPhoto(context.Context, *telego.SendPhotoParams) (*telego.Message, error) {
	return nil, errNoMediaSend
}
func (textOnlySender) SendVideo(context.Context, *telego.SendVideoParams) (*telego.Message, error) {
	return nil, errNoMediaSend
}
func (textOnlySender) SendAnimation(context.Context, *telego.SendAnimationParams) (*telego.Message, error) {
	return nil, errNoMediaSend
}
func (textOnlySender) SendDocument(context.Context, *telego.SendDocumentParams) (*telego.Message, error) {
	return nil, errNoMediaSend
}
func (textOnlySender) SendMediaGroup(context.Context, *telego.SendMediaGroupParams) ([]telego.Message, error) {
	return nil, errNoMediaSend
}
