package bot

// YouTube `si=` link sanitizer.
//
// Telegram clients append a `si` share-tracking parameter to YouTube
// links generated by the native share sheet. When a supergroup message
// carries such a link the bot deletes the original and reposts it,
// attributed, with `si` stripped. Everything else (path, fragment, all
// other query params, non-YouTube links, links without `si`) is left
// byte-for-byte intact.
//
// The host check is scoped: only YouTube hosts are sanitized, so a
// Spotify `?si=` (or any other service that uses the same param name)
// is never touched.
//
// Design notes / documented v1 gaps:
//   - text_link entities: the URL lives in entity.URL, not in the
//     message text. Rewriting it would require splicing the visible
//     text at UTF-16 offsets, which corrupts multi-plane text. We do
//     NOT rewrite text_link inline; instead the message is flagged
//     changed and the middleware uses the reply-fallback path (clean
//     links posted as a reply) rather than a corrupted repost.
//   - edited_message: OUT OF SCOPE for v1. The router only feeds
//     update.Message here; an edit that introduces a tracked link is
//     not re-sanitized. Explicit gap, not silently ignored.
//   - media groups / albums (MediaGroupID != ""): only the item that
//     carries the caption holds text. v1 sanitizes that one item and
//     leaves the sibling media in place; reposting the whole album as
//     a new group is deferred. Explicit gap.
//   - reply / forward: the repost is a fresh bot message, so the reply
//     thread link and the forward header are lost. Acceptable for v1;
//     we do not attempt to re-thread or rebuild a forward header.

import (
	"context"
	"html"
	"log/slog"
	"net/url"
	"regexp"
	"strings"

	"github.com/mymmrac/telego"
	th "github.com/mymmrac/telego/telegohandler"

	"github.com/veschin/bidlobot/internal/shared"
)

// youtubeHosts is the exact set of hosts whose `si` parameter is
// share-tracking. Host comparison is lower-cased with a leading "www."
// or "m." stripped. Any host not in this set is left untouched, which
// is what keeps Spotify/other `si=` links safe.
var youtubeHosts = map[string]struct{}{
	"youtube.com":          {},
	"youtu.be":             {},
	"youtube-nocookie.com": {},
	"music.youtube.com":    {},
}

// urlScanRe finds bare http(s) URLs and scheme-less youtu.be /
// youtube.com style links in plain text. It is intentionally
// conservative: it stops at whitespace and a small set of trailing
// punctuation so a link at the end of a sentence ("...watch?v=x&si=y.")
// does not swallow the period. Angle/paren wrappers are also excluded.
var urlScanRe = regexp.MustCompile(`(?i)\b((?:https?://|www\.|m\.)?(?:[a-z0-9-]+\.)*(?:youtube\.com|youtu\.be|youtube-nocookie\.com)\b[^\s<>"')\]]*)`)

// trailingPunct is stripped from a scanned token's tail so sentence
// punctuation that the regex may still catch (e.g. a trailing ")",
// handled above, or "," "." "!" "?") is not folded into the URL and
// then re-emitted. The stripped suffix is re-appended verbatim after
// cleaning so the surrounding text is preserved exactly.
const trailingPunct = ".,!?;:"

// StripShareTracking parses rawURL and, if its host (lower-cased,
// leading "www."/"m." removed) is a YouTube host AND the query carries
// a `si` key, removes ONLY that key. Every other query parameter, the
// path, and the fragment are preserved. The scheme is preserved as-is,
// including the scheme-less form (the bare host check transparently
// prepends a temporary scheme for parsing only).
//
// Returns (cleaned, true) when an `si` was removed, otherwise
// (rawURL, false) with the input returned verbatim.
//
// net/url applies two benign, RFC-sanctioned canonicalizations on the
// cleaned result: the scheme is lower-cased (schemes are
// case-insensitive) and a literal space in a surviving param value is
// re-emitted as '+' rather than %20 (query-equivalent). Host, path,
// fragment and all surviving param keys/values are otherwise byte-for-
// byte preserved, and the changed=false path returns the input
// untouched so non-YouTube and si-less links never see even these.
func StripShareTracking(rawURL string) (string, bool) {
	if rawURL == "" {
		return rawURL, false
	}

	// A scheme-less link ("youtu.be/x?si=y") parses with an empty Host
	// and the host folded into Path. Detect the missing scheme and
	// re-parse with a temporary "https://" prefix purely for host
	// extraction and query editing; the cleaned result is rebuilt
	// without the synthetic scheme so the user's original form (no
	// scheme) is preserved.
	hadScheme := true
	parseTarget := rawURL
	if !hasScheme(rawURL) {
		hadScheme = false
		parseTarget = "https://" + rawURL
	}

	u, err := url.Parse(parseTarget)
	if err != nil || u.Host == "" {
		return rawURL, false
	}

	if !isYouTubeHost(u.Host) {
		return rawURL, false
	}

	q := u.Query()
	if _, ok := q["si"]; !ok {
		return rawURL, false
	}
	q.Del("si")
	u.RawQuery = encodeQueryPreservingOrder(rawURL, q)

	cleaned := u.String()
	if !hadScheme {
		cleaned = strings.TrimPrefix(cleaned, "https://")
	}
	if cleaned == "" {
		// Defensive: a non-empty input that strips to empty should not
		// happen (we only remove one query key), but never emit "".
		return rawURL, false
	}
	return cleaned, true
}

// hasScheme reports whether s already starts with a URL scheme
// ("scheme://"). We only special-case the missing-scheme path, so a
// loose prefix check is enough; url.Parse does the real validation.
func hasScheme(s string) bool {
	i := strings.Index(s, "://")
	if i <= 0 {
		return false
	}
	for _, r := range s[:i] {
		if !(r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' ||
			r >= '0' && r <= '9' || r == '+' || r == '-' || r == '.') {
			return false
		}
	}
	return true
}

// isYouTubeHost lower-cases host, drops any port, strips a single
// leading "www." or "m." label, and checks the exact allowlist.
func isYouTubeHost(host string) bool {
	host = strings.ToLower(host)
	if i := strings.IndexByte(host, ':'); i >= 0 {
		host = host[:i]
	}
	switch {
	case strings.HasPrefix(host, "www."):
		host = host[len("www."):]
	case strings.HasPrefix(host, "m."):
		host = host[len("m."):]
	}
	_, ok := youtubeHosts[host]
	return ok
}

// encodeQueryPreservingOrder rebuilds the query string keeping the
// parameters in their original textual order. url.Values.Encode sorts
// keys alphabetically, which would reorder a user's link (v, then t,
// then list ...) even when nothing but `si` changed - a visible,
// unnecessary mutation. We walk the original raw query and re-emit
// every key still present in q, in first-seen order, then append any
// keys that q has but the original did not (none, in practice).
func encodeQueryPreservingOrder(rawURL string, q url.Values) string {
	rawQ := ""
	if i := strings.IndexByte(rawURL, '?'); i >= 0 {
		rawQ = rawURL[i+1:]
		if h := strings.IndexByte(rawQ, '#'); h >= 0 {
			rawQ = rawQ[:h]
		}
	}

	var b strings.Builder
	emitted := make(map[string]int)
	for _, pair := range strings.Split(rawQ, "&") {
		if pair == "" {
			continue
		}
		key := pair
		if eq := strings.IndexByte(pair, '='); eq >= 0 {
			key = pair[:eq]
		}
		decKey, err := url.QueryUnescape(key)
		if err != nil {
			decKey = key
		}
		vals, ok := q[decKey]
		if !ok {
			continue // dropped (this is the `si` we removed)
		}
		idx := emitted[decKey]
		if idx >= len(vals) {
			continue
		}
		if b.Len() > 0 {
			b.WriteByte('&')
		}
		b.WriteString(url.QueryEscape(decKey))
		b.WriteByte('=')
		b.WriteString(url.QueryEscape(vals[idx]))
		emitted[decKey] = idx + 1
	}
	return b.String()
}

// SanitizeMessageText scans text for tracked YouTube links - both bare
// URLs found by the scanner and `url`-type entities - and replaces each
// with its StripShareTracking result, preserving every other byte.
//
// text_link entities (URL in entity.URL, not in text) are detected too:
// if a text_link points at a tracked link the function reports
// changed=true WITHOUT mutating text (it cannot rewrite the hidden URL
// safely), so the caller falls back to the reply path instead of
// reposting corrupted text. This split (newText may equal text while
// changed is true) is intentional and documented.
func SanitizeMessageText(text string, entities []telego.MessageEntity) (string, bool) {
	changed := false

	// text_link entities: detect-only. If any points at a tracked
	// link, flag changed; the caller decides (reply-fallback). We must
	// not splice the visible text by entity offsets - offsets are
	// UTF-16 code units and editing them corrupts astral-plane text.
	for _, e := range entities {
		if e.Type == "text_link" && e.URL != "" {
			if _, c := StripShareTracking(e.URL); c {
				changed = true
			}
		}
	}

	if text == "" {
		return text, changed
	}

	newText := urlScanRe.ReplaceAllStringFunc(text, func(token string) string {
		// Peel trailing sentence punctuation so it is not absorbed into
		// the URL and then lost; re-attach it verbatim after cleaning.
		core := token
		suffix := ""
		for len(core) > 0 {
			last := core[len(core)-1]
			if strings.IndexByte(trailingPunct, last) >= 0 {
				suffix = string(last) + suffix
				core = core[:len(core)-1]
				continue
			}
			break
		}
		cleaned, c := StripShareTracking(core)
		if c {
			changed = true
			return cleaned + suffix
		}
		return token
	})

	return newText, changed
}

// youtubeMediaSender is the narrow rate-limited send surface this
// middleware needs. Production wires *tgclient.Client (which now
// implements the media sends in addition to SendMessage/DeleteMessage)
// so every repost shares the per-chat rate budget instead of bypassing
// it via the raw *telego.Bot - the same pattern stats.MessageSender and
// GamesSender use.
type youtubeMediaSender interface {
	SendMessage(ctx context.Context, params *telego.SendMessageParams) (*telego.Message, error)
	DeleteMessage(ctx context.Context, params *telego.DeleteMessageParams) error
	SendPhoto(ctx context.Context, params *telego.SendPhotoParams) (*telego.Message, error)
	SendVideo(ctx context.Context, params *telego.SendVideoParams) (*telego.Message, error)
	SendAnimation(ctx context.Context, params *telego.SendAnimationParams) (*telego.Message, error)
	SendDocument(ctx context.Context, params *telego.SendDocumentParams) (*telego.Message, error)
}

// Russian, neutral register, status glyph only - matches dm_text.go.
const (
	// Header of a reposted, sanitized message. %s = display name.
	msgYTRepostHeader = "\U0001F464 <b>%s</b> писал(а):"

	// Reply-fallback note when the bot could not delete the original
	// (no Delete Messages right) or the tracked link was inside a
	// text_link entity that cannot be rewritten in place. The cleaned
	// link(s) are listed before this note.
	msgYTFallbackNote = "Очищенная ссылка без трекинга (si удалён)."
)

// youtubeSanitizer is the supergroup middleware. Signature mirrors
// statsCountHandler's use in routes.go (a th.Handler closing over App).
//
// Per incoming update.Message in a supergroup it:
//   - skips bots / anonymous-admin / channel-as-sender / no-sender,
//     consistent with the stats exclusion set;
//   - computes sanitized text over (Text+Entities) and
//     (Caption+CaptionEntities); if nothing changed, passes through;
//   - on change: best-effort deletes the original via the rate-limited
//     sender. Delete failure -> reply with the cleaned link(s) + note
//     (never silent). Delete success -> repost by file_id (no size
//     limit) for media, else a text message, attributed, si stripped.
//
// It always calls ctx.Next(update) so sibling middleware (membership,
// stats) still run. Deleting the chat message does not remove the
// in-flight update object; keeping the chain consistent matches how
// statsCountHandler behaves. Ordering relative to stats is covered in
// the wiring notes returned with this change.
func youtubeSanitizer(a *App) th.Handler {
	return func(thctx *th.Context, update telego.Update) error {
		if act, newText, newCaption := sanitizeDecision(update.Message); act {
			handleSanitize(thctx.Context(), a.sanitizerSender(), a.log,
				update.Message, newText, newCaption)
		}
		// Always continue the chain so sibling middleware (membership,
		// stats) still run. Deleting the chat message does not remove
		// the in-flight update; keeping the chain consistent matches
		// statsCountHandler.
		return thctx.Next(update)
	}
}

// sanitizeDecision is the pure, fully unit-testable gate. It applies
// the same exclusion set as the stats counter (no sender / bot /
// anonymous-admin / channel-as-sender) and computes the sanitized text
// and caption. It returns act=false when the message must be passed
// through untouched, act=true with the new body/caption otherwise.
func sanitizeDecision(msg *telego.Message) (act bool, newText, newCaption string) {
	if msg == nil {
		return false, "", ""
	}
	if msg.From == nil || msg.From.IsBot ||
		shared.IsAnonymousAdmin(msg.From.ID) || msg.SenderChat != nil {
		return false, "", ""
	}
	newText, textChanged := SanitizeMessageText(msg.Text, msg.Entities)
	newCaption, capChanged := SanitizeMessageText(msg.Caption, msg.CaptionEntities)
	if !textChanged && !capChanged {
		return false, "", ""
	}
	return true, newText, newCaption
}

// sanitizerSender returns the rate-limited media-capable client. It is
// a method (not a direct a.sender reference in the handler) so the
// narrow interface assertion lives in one place and the type mismatch -
// shared.TelegramAPI lacks the media methods - is resolved here via the
// concrete client. a.sender is the *tgclient.Client; the type assertion
// is safe because production always constructs it so, and a failure is
// surfaced (logged + degraded to text-only) rather than panicking.
func (a *App) sanitizerSender() youtubeMediaSender {
	if s, ok := a.sender.(youtubeMediaSender); ok {
		return s
	}
	// Degraded mode: the configured sender does not expose media sends.
	// Wrap the text/delete surface so the sanitizer still strips links
	// (text reposts + reply-fallback) instead of crashing. Logged once
	// per call site by the caller.
	return textOnlySender{a.sender}
}

// textOnlySender adapts a SendMessage/DeleteMessage-only client to the
// media interface by failing media sends with a sentinel error, which
// handleSanitize treats as "repost not possible" and routes to the
// reply-fallback. This keeps the feature safe if wiring ever passes a
// non-media client; it is not the expected production path.
type textOnlySender struct {
	api interface {
		SendMessage(ctx context.Context, params *telego.SendMessageParams) (*telego.Message, error)
		DeleteMessage(ctx context.Context, params *telego.DeleteMessageParams) error
	}
}

var errNoMediaSend = &mediaUnsupportedError{}

type mediaUnsupportedError struct{}

func (*mediaUnsupportedError) Error() string {
	return "tgclient: media send not supported by configured sender"
}

func (t textOnlySender) SendMessage(ctx context.Context, p *telego.SendMessageParams) (*telego.Message, error) {
	return t.api.SendMessage(ctx, p)
}
func (t textOnlySender) DeleteMessage(ctx context.Context, p *telego.DeleteMessageParams) error {
	return t.api.DeleteMessage(ctx, p)
}
func (textOnlySender) SendPhoto(context.Context, *telego.SendPhotoParams) (*telego.Message, error) {
	return nil, errNoMediaSend
}
func (textOnlySender) SendVideo(context.Context, *telego.SendVideoParams) (*telego.Message, error) {
	return nil, errNoMediaSend
}
func (textOnlySender) SendAnimation(context.Context, *telego.SendAnimationParams) (*telego.Message, error) {
	return nil, errNoMediaSend
}
func (textOnlySender) SendDocument(context.Context, *telego.SendDocumentParams) (*telego.Message, error) {
	return nil, errNoMediaSend
}

// handleSanitize performs the delete + repost (or reply-fallback). It
// is split out so it is unit-testable with a recording fake sender
// without driving the whole th.Context machinery.
func handleSanitize(
	ctx context.Context,
	snd youtubeMediaSender,
	log *slog.Logger,
	msg *telego.Message,
	newText, newCaption string,
) {
	display := shared.UserDisplay(msg.From.Username, msg.From.FirstName)
	header := sprintfHeader(display)

	// text_link-only change: SanitizeMessageText reports changed=true
	// but leaves the body unchanged because the tracked URL is hidden
	// in an entity. Detect that case (visible body identical to the
	// original) and take the reply-fallback rather than reposting an
	// unchanged-looking body that still shows the tracked link.
	bodyVisiblyChanged := (msg.Text != "" && newText != msg.Text) ||
		(msg.Caption != "" && newCaption != msg.Caption)

	cleanedLinks := collectCleanedLinks(msg)

	if !bodyVisiblyChanged {
		// Nothing we can safely rewrite inline (text_link case). Do not
		// delete a message we cannot faithfully reproduce; reply with
		// the clean link(s) instead so the value is still delivered.
		replyFallback(ctx, snd, log, msg, cleanedLinks)
		return
	}

	// Repost FIRST, delete only on success. A failed repost must never
	// destroy the user's message - a stale si= link is strictly better
	// than lost content.
	if err := repost(ctx, snd, msg, header, newText, newCaption); err != nil {
		log.Warn("youtube sanitizer: repost failed; leaving original intact (no delete)",
			"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID(), "error", err)
		return
	}
	if delErr := snd.DeleteMessage(ctx, &telego.DeleteMessageParams{
		ChatID:    telego.ChatID{ID: msg.Chat.ID},
		MessageID: msg.GetMessageID(),
	}); delErr != nil {
		// Reposted copy is already live; we just can't remove the
		// original (no Delete right). A visible duplicate carrying the
		// tracked link is the lesser evil vs. destroying content.
		log.Info("youtube sanitizer: reposted but delete failed; original kept",
			"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID(), "error", delErr)
	}
}

// repost re-sends the message as the bot with the sanitized body.
// Media is resent by file_id (no upload, no 50MB bot-send cap, since
// file_id reuse is server-side). Entities are intentionally dropped:
// stripping `si` shortens the text, so the original entity offsets
// (UTF-16 code units into the OLD text) no longer line up; carrying
// them would mangle formatting. The body is HTML-escaped plain text
// under ParseMode HTML, and the header is the only markup.
func repost(
	ctx context.Context,
	snd youtubeMediaSender,
	msg *telego.Message,
	header, newText, newCaption string,
) error {
	captionBody := header
	if newCaption != "" {
		captionBody += "\n" + html.EscapeString(newCaption)
	}

	switch {
	case len(msg.Photo) > 0:
		_, err := snd.SendPhoto(ctx, &telego.SendPhotoParams{
			ChatID:    telego.ChatID{ID: msg.Chat.ID},
			Photo:     telego.InputFile{FileID: largestPhotoFileID(msg.Photo)},
			Caption:   captionBody,
			ParseMode: telego.ModeHTML,
		})
		return err

	case msg.Video != nil:
		_, err := snd.SendVideo(ctx, &telego.SendVideoParams{
			ChatID:    telego.ChatID{ID: msg.Chat.ID},
			Video:     telego.InputFile{FileID: msg.Video.FileID},
			Caption:   captionBody,
			ParseMode: telego.ModeHTML,
		})
		return err

	case msg.Animation != nil:
		_, err := snd.SendAnimation(ctx, &telego.SendAnimationParams{
			ChatID:    telego.ChatID{ID: msg.Chat.ID},
			Animation: telego.InputFile{FileID: msg.Animation.FileID},
			Caption:   captionBody,
			ParseMode: telego.ModeHTML,
		})
		return err

	case msg.Document != nil:
		_, err := snd.SendDocument(ctx, &telego.SendDocumentParams{
			ChatID:    telego.ChatID{ID: msg.Chat.ID},
			Document:  telego.InputFile{FileID: msg.Document.FileID},
			Caption:   captionBody,
			ParseMode: telego.ModeHTML,
		})
		return err

	default:
		body := header
		if newText != "" {
			body += "\n" + html.EscapeString(newText)
		}
		_, err := snd.SendMessage(ctx, &telego.SendMessageParams{
			ChatID:    telego.ChatID{ID: msg.Chat.ID},
			Text:      body,
			ParseMode: telego.ModeHTML,
		})
		return err
	}
}

// replyFallback posts the cleaned link(s) as a reply to the original
// (which still exists in this path) plus a one-line note. Never silent:
// a send error is logged. Used when the original cannot be deleted or
// the tracked link is inside a text_link entity we will not rewrite.
func replyFallback(
	ctx context.Context,
	snd youtubeMediaSender,
	log *slog.Logger,
	msg *telego.Message,
	cleanedLinks []string,
) {
	var b strings.Builder
	if len(cleanedLinks) > 0 {
		b.WriteString(html.EscapeString(strings.Join(cleanedLinks, "\n")))
		b.WriteString("\n")
	}
	b.WriteString(msgYTFallbackNote)

	_, err := snd.SendMessage(ctx, &telego.SendMessageParams{
		ChatID: telego.ChatID{ID: msg.Chat.ID},
		Text:   b.String(),
		ReplyParameters: &telego.ReplyParameters{
			MessageID: msg.GetMessageID(),
		},
		ParseMode: telego.ModeHTML,
	})
	if err != nil {
		log.Warn("youtube sanitizer: reply-fallback send failed",
			"chat_id", msg.Chat.ID, "message_id", msg.GetMessageID(), "error", err)
	}
}

// collectCleanedLinks returns the distinct cleaned forms of every
// tracked link in the message - bare URLs in text/caption and the URLs
// of url / text_link entities. Used by the reply-fallback so the user
// still gets a copy-pasteable clean link even when an in-place rewrite
// is impossible.
func collectCleanedLinks(msg *telego.Message) []string {
	seen := make(map[string]struct{})
	var out []string

	add := func(raw string) {
		if cleaned, c := StripShareTracking(raw); c {
			if _, dup := seen[cleaned]; !dup {
				seen[cleaned] = struct{}{}
				out = append(out, cleaned)
			}
		}
	}

	for _, e := range msg.Entities {
		if e.Type == "text_link" && e.URL != "" {
			add(e.URL)
		}
	}
	for _, e := range msg.CaptionEntities {
		if e.Type == "text_link" && e.URL != "" {
			add(e.URL)
		}
	}
	for _, m := range []string{msg.Text, msg.Caption} {
		for _, tok := range urlScanRe.FindAllString(m, -1) {
			core := strings.TrimRight(tok, trailingPunct)
			add(core)
		}
	}
	return out
}

// largestPhotoFileID returns the file_id of the highest-resolution
// PhotoSize so the repost keeps the original quality. Telegram orders
// the slice ascending but we pick by area defensively rather than
// trusting order.
func largestPhotoFileID(sizes []telego.PhotoSize) string {
	best := sizes[0]
	bestArea := best.Width * best.Height
	for _, s := range sizes[1:] {
		if a := s.Width * s.Height; a > bestArea {
			best, bestArea = s, a
		}
	}
	return best.FileID
}

func sprintfHeader(display string) string {
	// display comes from shared.UserDisplay and is INERT: the handle
	// form has NO leading '@' and the first-name form is HTML-escaped.
	// This header is reposted publicly into the group, so an '@handle'
	// here would notify the attributed member on every sanitized link;
	// inert text is required (do not "restore" the '@'). The %s slot
	// sits inside <b> so no further escaping is applied to avoid double
	// encoding.
	return strings.Replace(msgYTRepostHeader, "%s", display, 1)
}

func firstNonEmpty(a, b string) string {
	if a != "" {
		return a
	}
	return b
}
